django-crud-modals/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views


urlpatterns = patterns('',
    url(r'^$', views.Consultar.as_view(), name='consultar'),
    url(r'^registrar$', views.Registrar.as_view(), name='registrar'),
    url(r'^editar/(?P<pk>\d+)$', views.Editar.as_view(), name='editar'),
    url(r'^borrar/(?P<pk>\d+)$', views.Borrar.as_view(), name='borrar'),
)

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Persona(models.Model):
    nombre = models.CharField(max_length=200)
    cedula = models.CharField(max_length=8)

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('registro:editar', kwargs={'pk': self.pk})

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import *
from django.forms import (
    TextInput, CharField, Select, RadioSelect, Textarea, CheckboxInput, DateTimeField
)
from datetime import *


class PersonaForm(forms.ModelForm):
    """
    Formulario que gestiona los campos de un producto.
    """
    nombre = forms.CharField(label='Nombre', widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    cedula = forms.CharField(label='Cédula', widget=TextInput(attrs={
        'class':'form-control input-md form_style',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    class Meta:
        model = Persona
        fields = '__all__'

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from registro.models import Persona
from registro.forms import PersonaForm
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import redirect


class Consultar(ListView):
    model = Persona

    def get_context_data(self, **kwargs):
        queryset = kwargs.pop('object_list', self.object_list)
        page_size = self.get_paginate_by(queryset)
        context_object_name = self.get_context_object_name(queryset)
        form = PersonaForm()
        if page_size:
            paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, page_size)
            context = {
                'paginator': paginator,
                'page_obj': page,
                'is_paginated': is_paginated,
                'object_list': queryset,
            }
        else:
            context = {
                'paginator': None,
                'page_obj': None,
                'is_paginated': False,
                'object_list': queryset,
                'form':form,
            }
        if context_object_name is not None:
            context[context_object_name] = queryset
        context.update(kwargs)
        return super(Consultar, self).get_context_data(**context)


class Registrar(CreateView):
    model = Persona
    form_class = PersonaForm
    success_url = reverse_lazy('registro:consultar')

    def get_context_data(self, **kwargs):
        queryset = Persona.objects.all()
        context = {
            'object_list': queryset,
        }
        if self.object:
            context['object'] = self.object
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super(Registrar, self).get_context_data(**context)


class Editar(UpdateView):
    template_name = "registro/persona_form_update.html"
    model = Persona
    form_class = PersonaForm
    success_url = reverse_lazy('registro:consultar')

    def get_context_data(self, **kwargs):
        queryset = Persona.objects.all()
        context = {
            'object_list': queryset,
        }
        if self.object:
            context['object'] = self.object
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super(Editar, self).get_context_data(**context)


class Borrar(DeleteView):
    model = Persona
    success_url = reverse_lazy('registro:consultar')

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>
    <!-- navbar class
    ================================================== -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Django CRUD Bootstrap modals</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'registro:consultar' %}">Lista</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- navbar class end -->
    <!-- container class
    ================================================== -->
    <div class="container theme-showcase" role="main">
      <div class="well">
      {% block cuerpo %}
      {% endblock %}
      </div>
    </div>
    <!-- container class end -->
  </body>
</html>

registro/templates/registro/modals.html
<!-- Modal con el formulario de registro de personas -->
<div class="modal fade" id="modal-registrar" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h1 class="modal-title">Registrar persona</h1>
      </div>
      <div class="modal-body">
      <form action="{% url 'registro:registrar' %}" method="post">{% csrf_token %}
        <label>Nombre:</label>
        <br />
        {{ form.nombre }}
        {% if form.nombre.errors %}
          <br />
          <b>Alert: </b>{{ form.nombre.errors}}
        {% endif %}
        <br>
        <br>
        <label>Cédula:</label>
        <br />
        {{ form.cedula }}
        {% if form.cedula.errors %}
          <br />
          <b>Alert: </b>{{ form.cedula.errors}}
        {% endif %}
        <br>
        <br>
        <button type="button" class="btn btn-default" data-dismiss="modal">CANCELAR</button>
        <button class="btn btn-success" type="submit">REGISTRAR</button>
        </form>
      </div>
    </div>
  </div>
</div>

registro/templates/registro/persona_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Borrar{% endblock %}
{% block cuerpo %}
<h1>Borrar persona</h1>
<br />
<form method="post">{% csrf_token %}
  ¿Está seguro que desea borrar a "{{ object }}" ?
  <button class="btn btn-danger" type="submit">BORRAR</button>
</form>
{% endblock %}

registro/templates/registro/persona_form.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de personas{% endblock %}
{% block cuerpo %}
<h1>Lista de personas</h1>
<br />
<button class="btn btn-success" data-toggle="modal" data-target="#modal-registrar">REGISTRAR</button>
<br />
<br />
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">ID</th>
      <th class="text-center">Nombre</th>
      <th class="text-center">Cédula</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for persona in object_list %}
  <tr>
    <td class="text-center">{{ persona.id }}</td>
    <td class="text-center">{{ persona.nombre }}</td>
    <td class="text-center">{{ persona.cedula }}</td>
    <td class="text-center">
      <a href="{% url 'registro:editar' persona.id %}">
        <button class="btn btn-info">EDITAR</button>
      </a>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal{{ persona.id }}">BORRAR</button>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include "registro/modals.html" %}
<script type="text/javascript">
$(document).ready(function(){
  $('.modal').modal('show');
});
</script>
{% endblock %}

registro/templates/registro/persona_form_update.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de personas{% endblock %}
{% block cuerpo %}
<h1>Lista de personas</h1>
<br />
<button class="btn btn-success" data-toggle="modal" data-target="#modal-registrar">REGISTRAR</button>
<br />
<br />
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">ID</th>
      <th class="text-center">Nombre</th>
      <th class="text-center">Cédula</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for persona in object_list %}
  <tr>
    <td class="text-center">{{ persona.id }}</td>
    <td class="text-center">{{ persona.nombre }}</td>
    <td class="text-center">{{ persona.cedula }}</td>
    <td class="text-center">
      <a href="{% url 'registro:editar' persona.id %}">
        <button class="btn btn-info">EDITAR</button>
      </a>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal{{ persona.id }}">BORRAR</button>
      <!-- Modal con el formulario para borrar un registro -->
      <div class="modal fade" id="myModal{{ persona.id }}" role="dialog">
        <div class="modal-dialog modal-md">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Borrar registro</h4>
            </div>
            <div class="modal-body">
              <form action="{% url 'registro:borrar' persona.id %}" method="post">{% csrf_token %}
                ¿Está seguro que desea borrar a "{{ persona.nombre }}"?
                <br><br>
                <button type="button" class="btn btn-default" data-dismiss="modal">CANCELAR</button>
                <button class="btn btn-danger" type="submit">BORRAR</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include "registro/modals.html" %}
<div class="modal fade" id="modal-actualizar" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h1 class="modal-title">Actualizar persona</h1>
      </div>
      <div class="modal-body">
        <form method="post" action="/editar/{{ persona.id }}">{% csrf_token %}
          <label>Nombre:</label>
          <br />
          {{ form.nombre }}
          {% if form.nombre.errors %}
            <br />
            <b>Alert: </b>{{ form.nombre.errors}}
          {% endif %}
          <br>
          <br>
          <label>Cédula:</label>
          <br />
          {{ form.cedula }}
          {% if form.cedula.errors %}
            <br />
            <b>Alert: </b>{{ form.cedula.errors}}
          {% endif %}
          <br /><br />
          <a href="{% url 'registro:consultar' %}">
            <button type="button" class="btn btn-default">CANCELAR</button>
          </a>
          <button class="btn btn-success" type="submit">ACTUALIZAR</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
  $('#modal-actualizar').modal('show');
});
</script>
<script type="text/javascript">
$(document).ready(function() {
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

registro/templates/registro/persona_list.html
{% extends "registro/base.html" %}
{% block titulo %}Lista{% endblock %}
{% block cuerpo %}
<h1>Lista de personas</h1>
<br />
<button class="btn btn-success" data-toggle="modal" data-target="#modal-registrar">REGISTRAR</button>
<br />
<br />
{% if object_list %}
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">ID</th>
      <th class="text-center">Nombre</th>
      <th class="text-center">Cédula</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for persona in object_list %}
  <tr>
    <td class="text-center">{{ persona.id }}</td>
    <td class="text-center">{{ persona.nombre }}</td>
    <td class="text-center">{{ persona.cedula }}</td>
    <td class="text-center">
      <a href="{% url 'registro:editar' persona.id %}">
        <button class="btn btn-info">EDITAR</button>
      </a>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal{{ persona.id }}">BORRAR</button>
      <!-- Modal con el formulario para borrar un registro -->
      <div class="modal fade" id="myModal{{ persona.id }}" role="dialog">
        <div class="modal-dialog modal-md">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Borrar registro</h4>
            </div>
            <div class="modal-body">
              <form action="{% url 'registro:borrar' persona.id %}" method="post">{% csrf_token %}
                ¿Está seguro que desea borrar a "{{ persona.nombre }}"?
                <br><br>
                <button type="button" class="btn btn-default" data-dismiss="modal">CANCELAR</button>
                <button class="btn btn-danger" type="submit">BORRAR</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
  <h3>No hay objetos registrados</h3>
{% endif %}
{% include "registro/modals.html" %}
<script type="text/javascript">
$(document).ready(function() {
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}